# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
    - run: yarn install
    - run: yarn run build --if-present
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v5.0.0
      with:
        # Path of the directory containing the static assets.
        path: ./dist
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v3.0.2-node.24
      
